# Generated by Django 5.2.8 on 2026-02-13 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0022_alter_profile_phone'),
        ('comment_post', '0003_alter_comment_content'),
        ('post', '0008_adcampaign_sponsoredpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('premium', 'Premium - Paid subscription'), ('fire', 'Fire - High activity'), ('verified', 'Verified - Identity confirmed'), ('influencer', 'Influencer - High engagement')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(default='#000000', max_length=20)),
                ('duration_days', models.IntegerField(blank=True, help_text='Durée en jours pour expiration automatique', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IDVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_front', models.ImageField(upload_to='verification_ids/front/')),
                ('id_card_back', models.ImageField(blank=True, null=True, upload_to='verification_ids/back/')),
                ('selfie_with_id', models.ImageField(blank=True, null=True, upload_to='verification_ids/selfie/')),
                ('full_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=100)),
                ('id_type', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_verification', to='app.profile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('subscription_start', models.DateTimeField(blank=True, null=True)),
                ('subscription_end', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_method', models.CharField(blank=True, max_length=50, null=True)),
                ('verification_doc_id', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_score', models.IntegerField(default=0)),
                ('last_activity_check', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='app.profile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_certifications', to=settings.AUTH_USER_MODEL)),
                ('certification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certfications.certificationtype')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('profile', 'certification_type')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('certification', 'Certification Premium'), ('post_boost', 'Post Boost'), ('other', 'Other')], default='other', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_type', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_start', models.DateTimeField(blank=True, null=True)),
                ('subscription_end', models.DateTimeField(blank=True, null=True)),
                ('boost_start', models.DateTimeField(blank=True, null=True)),
                ('boost_end', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.adcampaign')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.post')),
                ('sponsored_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.sponsoredpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stripe_checkout_session_id'], name='certficatio_stripe__ad4530_idx'), models.Index(fields=['stripe_customer_id'], name='certficatio_stripe__f5e5e7_idx'), models.Index(fields=['status'], name='certficatio_status_5dfc65_idx'), models.Index(fields=['payment_type'], name='certficatio_payment_63a628_idx'), models.Index(fields=['user', 'payment_type'], name='certficatio_user_id_2dfc70_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('comment', 'Comment'), ('rating', 'Rating'), ('share', 'Share'), ('save', 'Save'), ('boost_purchase', 'Boost Purchase'), ('click', 'Click'), ('time_spent', 'Time Spent'), ('follow', 'Follow'), ('mention', 'Mention'), ('report', 'Report'), ('hide', 'Hide')], max_length=20)),
                ('value', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certification_interactions', to='post.category')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certification_interactions', to='comment_post.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certification_interactions', to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'interaction_type'], name='certficatio_user_id_121317_idx'), models.Index(fields=['post', 'interaction_type'], name='certficatio_post_id_41c110_idx'), models.Index(fields=['user', 'post'], name='certficatio_user_id_2e83e1_idx'), models.Index(fields=['created_at'], name='certficatio_created_0d906c_idx')],
                'unique_together': {('user', 'post', 'interaction_type')},
            },
        ),
    ]
