# Generated by Django 5.2.7 on 2025-12-13 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='files',
        ),
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='post_files/%Y/%m/%d/')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_files', to='post.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
