# Generated by Django 5.2.8 on 2026-02-13 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_postview_userinteraction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('priority', models.IntegerField(choices=[(1, 'Normal'), (2, 'Élevée'), (3, 'Très élevée')], default=1)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('paused', 'En pause'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='draft', max_length=20)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_categories', models.ManyToManyField(blank=True, related_name='ad_campaigns', to='post.category')),
                ('target_tags', models.ManyToManyField(blank=True, related_name='ad_campaigns', to='post.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsoredPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('standard', 'Post standard'), ('premium', 'Post premium'), ('featured', 'Post en vedette'), ('spotlight', 'Post spotlight')], default='standard', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('boost_start', models.DateTimeField()),
                ('boost_end', models.DateTimeField()),
                ('boost_multiplier', models.FloatField(default=1.0, help_text='Multiplicateur de visibilité')),
                ('always_on_top', models.BooleanField(default=False, help_text='Toujours afficher en haut')),
                ('featured_in_feed', models.BooleanField(default=True, help_text='Afficher dans le flux principal')),
                ('featured_in_category', models.BooleanField(default=False, help_text='Afficher en vedette dans la catégorie')),
                ('boosted_views', models.IntegerField(default=0)),
                ('boosted_clicks', models.IntegerField(default=0)),
                ('boosted_engagement', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_posts', to='post.adcampaign')),
                ('original_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_post', to='post.post')),
            ],
            options={
                'ordering': ['-boost_multiplier', '-created_at'],
            },
        ),
    ]
