# Generated by Django 5.2.7 on 2025-12-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
