# Generated by Django 5.2.7 on 2025-12-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_post', '0002_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
