# Generated by Django 5.2.7 on 2025-12-03 02:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='helpful_users',
            field=models.ManyToManyField(blank=True, related_name='helpful_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
