# Generated by Django 5.2.7 on 2026-01-08 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0018_passwordresetcode'),
        ('comment_post', '0003_alter_comment_content'),
        ('feedback_post', '0002_alter_rating_post'),
        ('messaging', '0012_message_is_system_message_and_more'),
        ('post', '0006_alter_category_options_category_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('message', 'Message'), ('post', 'Post'), ('comment', 'Commentaire'), ('profile', 'Profil'), ('feedback', 'Feedback')], max_length=20, verbose_name='Type de contenu')),
                ('content_id', models.PositiveIntegerField(verbose_name='ID du contenu')),
                ('report_type', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harcèlement'), ('hate_speech', 'Discours haineux'), ('inappropriate', 'Contenu inapproprié'), ('copyright', 'Violation de copyright'), ('false_info', 'Fausse information'), ('other', 'Autre')], max_length=20, verbose_name='Type de signalement')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Raison détaillée')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('under_review', "En cours d'examen"), ('resolved', 'Résolu'), ('dismissed', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Examiné le')),
                ('moderator_notes', models.TextField(blank=True, null=True, verbose_name='Notes du modérateur')),
                ('action_taken', models.TextField(blank=True, null=True, verbose_name='Action prise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='comment_post.comment')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='feedback_post.rating')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='messaging.message')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='post.post')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app.profile')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='Signaleur')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Modérateur')),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('delete', 'Supprimer le contenu'), ('warn', "Avertir l'utilisateur"), ('suspend', "Suspendre l'utilisateur"), ('ban', "Bannir l'utilisateur"), ('ignore', 'Ignorer le signalement'), ('edit', 'Modifier le contenu')], max_length=20)),
                ('description', models.TextField(verbose_name="Description de l'action")),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (jours)')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='report.report')),
            ],
            options={
                'verbose_name': 'Action de modération',
                'verbose_name_plural': 'Actions de modération',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['content_type', 'content_id'], name='report_repo_content_5980f1_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='report_repo_status_7d0999_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='report_repo_created_be46cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('reporter', 'content_type', 'content_id')},
        ),
    ]
