# Generated by Django 5.2.7 on 2026-01-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_report_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate_speech', 'Discours haineux'), ('inappropriate', 'Contenu inapproprié'), ('copyright', 'Violation de copyright'), ('false_info', 'Fausse information'), ('other', 'Autre')], max_length=20, verbose_name='Type de signalement'),
        ),
    ]
