# Generated by Django 5.2.7 on 2026-01-13 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_report_report_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterModelOptions(
            name='reportaction',
            options={'ordering': ['-performed_at'], 'verbose_name': 'Moderation Action', 'verbose_name_plural': 'Moderation Actions'},
        ),
        migrations.AlterField(
            model_name='report',
            name='action_taken',
            field=models.TextField(blank=True, null=True, verbose_name='Action Taken'),
        ),
        migrations.AlterField(
            model_name='report',
            name='content_id',
            field=models.PositiveIntegerField(verbose_name='Content ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='content_type',
            field=models.CharField(choices=[('message', 'Message'), ('post', 'Post'), ('comment', 'Comment'), ('profile', 'Profile'), ('feedback', 'Feedback')], max_length=20, verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='report',
            name='moderator_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Moderator Notes'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Detailed Reason'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate_speech', 'Hate Speech'), ('inappropriate', 'Inappropriate Content'), ('copyright', 'Copyright Infringement'), ('false_info', 'False Information'), ('other', 'Other')], max_length=20, verbose_name='Report Type'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='Reporter'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Moderator'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reportaction',
            name='action_type',
            field=models.CharField(choices=[('delete', 'Delete Content'), ('warn', 'Warn User'), ('suspend', 'Suspend User'), ('ban', 'Ban User'), ('ignore', 'Ignore Report'), ('edit', 'Edit Content')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reportaction',
            name='description',
            field=models.TextField(verbose_name='Action Description'),
        ),
        migrations.AlterField(
            model_name='reportaction',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (days)'),
        ),
        migrations.AlterField(
            model_name='reportaction',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Moderator'),
        ),
    ]
