# Generated by Django 5.2.7 on 2026-01-13 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0012_message_is_system_message_and_more'),
        ('report', '0005_alter_report_options_alter_reportaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='messaging.conversation'),
        ),
        migrations.AlterField(
            model_name='report',
            name='content_type',
            field=models.CharField(choices=[('message', 'Message'), ('post', 'Post'), ('comment', 'Comment'), ('profile', 'Profile'), ('feedback', 'Feedback'), ('conversation', 'conversation')], max_length=20, verbose_name='Content Type'),
        ),
    ]
