# Generated by Django 5.2.7 on 2026-01-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_report_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='content_type',
            field=models.CharField(choices=[('message', 'Message'), ('post', 'Post'), ('comment', 'Comment'), ('profile', 'Profile'), ('feedback', 'Feedback'), ('conversation', 'Conversation')], max_length=20, verbose_name='Content Type'),
        ),
    ]
