# Generated by Django 5.2.7 on 2026-01-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_alter_report_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate_speech', 'Hate Speech'), ('inappropriate', 'Inappropriate Content'), ('copyright', 'Copyright Infringement'), ('false_info', 'False Information'), ('nudity_content', 'Nudity Content'), ('other', 'Other')], max_length=20, verbose_name='Report Type'),
        ),
    ]
