# Generated by Django 5.2.8 on 2025-11-14 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_post_category_profile_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
