# Generated by Django 5.2.8 on 2025-11-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_profile_address_profile_city_profile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_bio',
            field=models.ImageField(blank=True, null=True, upload_to='profile_bio/'),
        ),
    ]
