# Generated by Django 5.2.8 on 2025-11-18 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_post_like_post_average_rating_and_more'),
        ('feedback_post', '0002_alter_rating_post'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
