# Generated by Django 5.2.7 on 2025-12-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_for_everyone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_for_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_for_sender',
            field=models.BooleanField(default=False),
        ),
    ]
