# Generated by Django 5.2.7 on 2025-12-29 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_conversation_created_by_conversation_is_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='can_anyone_invite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='group_photo',
            field=models.ImageField(blank=True, null=True, upload_to='group_photos/'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='group_type',
            field=models.CharField(choices=[('private', 'Conversation Privée'), ('group_private', 'Groupe Privé'), ('group_public', 'Groupe Public')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='max_participants',
            field=models.IntegerField(default=100),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_group', 'group_type'], name='messaging_c_is_grou_7e6fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_by'], name='messaging_c_created_1ea16c_idx'),
        ),
    ]
