# Generated by Django 5.2.7 on 2025-12-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_groupblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupjoinrequest',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
