# Generated by Django 5.2.7 on 2026-01-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_groupjoinrequest_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_system_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='system_message_type',
            field=models.CharField(blank=True, choices=[('user_joined', 'User joined'), ('user_left', 'User left'), ('user_removed', 'User removed'), ('group_photo_changed', 'Group photo changed'), ('group_name_changed', 'Group name changed'), ('admin_promoted', 'Admin promoted'), ('admin_demoted', 'Admin demoted'), ('user_invited', 'User invited')], max_length=50, null=True),
        ),
    ]
