# Generated by Django 5.2.7 on 2026-01-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_message_is_system_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_system_message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='system_message_type',
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('user', 'User Message'), ('system', 'System Message')], default='user', max_length=20),
        ),
    ]
