# Generated by Django 5.2.7 on 2026-01-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_remove_message_is_system_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_system_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='system_message_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
