# Generated by Django 5.2.7 on 2026-01-15 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0012_message_is_system_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupblock',
            name='blocked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_users_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupblock',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_blocks', to='messaging.conversation'),
        ),
        migrations.CreateModel(
            name='BlockSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_profile_from_blocked', models.BooleanField(default=True)),
                ('hide_online_status_from_blocked', models.BooleanField(default=True)),
                ('hide_last_seen_from_blocked', models.BooleanField(default=True)),
                ('notify_on_block', models.BooleanField(default=True)),
                ('notify_on_unblock', models.BooleanField(default=True)),
                ('auto_block_spam_users', models.BooleanField(default=False)),
                ('spam_report_threshold', models.IntegerField(default=3)),
                ('max_blocks_allowed', models.IntegerField(default=100)),
                ('block_duration_default', models.IntegerField(default=0, help_text='Durée par défaut en jours (0 = permanent)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='block_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('user', 'Blocage Utilisateur'), ('profile', 'Blocage Profil'), ('both', 'Blocage Complet')], default='both', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blocker', 'blocked', 'is_active'], name='messaging_b_blocker_36f7ba_idx'), models.Index(fields=['created_at'], name='messaging_b_created_9728c3_idx')],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
        migrations.CreateModel(
            name='BlockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('block', 'Blocage'), ('unblock', 'Déblocage'), ('auto_block', 'Blocage Automatique')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('duration_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_target_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action', 'created_at'], name='messaging_b_user_id_f0a60d_idx'), models.Index(fields=['target_user', 'created_at'], name='messaging_b_target__ff9d51_idx')],
            },
        ),
    ]
