# Generated by Django 5.2.7 on 2026-01-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0013_alter_groupblock_blocked_by_alter_groupblock_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('user', 'Block User'), ('profile', 'Block Profile '), ('both', 'Block Both')], default='both', max_length=20),
        ),
    ]
