# Generated by Django 5.2.7 on 2026-01-30 21:09

import messaging.encrypted_fields
import messaging.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0014_alter_block_block_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupblock',
            options={'verbose_name': 'Group Block'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.RemoveIndex(
            model_name='block',
            name='messaging_b_blocker_36f7ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='block',
            name='messaging_b_created_9728c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='blockhistory',
            name='messaging_b_user_id_f0a60d_idx',
        ),
        migrations.RemoveIndex(
            model_name='blockhistory',
            name='messaging_b_target__ff9d51_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.AddField(
            model_name='conversation',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='message',
            name='content_hash',
            field=models.CharField(blank=True, help_text='Hash SHA-256 du contenu décrypté', max_length=64),
        ),
        migrations.AddField(
            model_name='message',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='edit_history',
            field=messaging.encrypted_fields.EncryptedJSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='encrypted_content',
            field=messaging.encrypted_fields.EncryptedTextField(blank=True, help_text='Contenu du message encrypté', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='encrypted_file_path',
            field=messaging.encrypted_fields.EncryptedCharField(blank=True, help_text='Chemin du fichier encrypté', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='encrypted_session_key',
            field=messaging.encrypted_fields.EncryptedTextField(blank=True, help_text='Clé de session encryptée avec la clé publique du destinataire'),
        ),
        migrations.AddField(
            model_name='message',
            name='encryption_nonce',
            field=models.CharField(default=messaging.models.default_encryption_nonce, help_text="Nonce utilisé pour l'encryption AES-GCM", max_length=32),
        ),
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=messaging.encrypted_fields.EncryptedJSONField(default=dict, help_text='Métadonnées encryptées (type, taille, etc.)'),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('user', 'Block User'), ('profile', 'Block Profile'), ('both', 'Block Both')], default='both', max_length=20),
        ),
        migrations.AlterField(
            model_name='block',
            name='reason',
            field=messaging.encrypted_fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockhistory',
            name='metadata',
            field=messaging.encrypted_fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='blockhistory',
            name='reason',
            field=messaging.encrypted_fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blocksettings',
            name='block_duration_default',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='description',
            field=messaging.encrypted_fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='location',
            field=messaging.encrypted_fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='name',
            field=messaging.encrypted_fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='rules',
            field=messaging.encrypted_fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='tags',
            field=messaging.encrypted_fields.EncryptedJSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='groupblock',
            name='metadata',
            field=messaging.encrypted_fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='groupblock',
            name='reason',
            field=messaging.encrypted_fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupcategory',
            name='description',
            field=messaging.encrypted_fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='groupfeedback',
            name='comment',
            field=messaging.encrypted_fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupjoinrequest',
            name='message',
            field=messaging.encrypted_fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupjoinrequest',
            name='metadata',
            field=messaging.encrypted_fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='groupjoinrequest',
            name='review_notes',
            field=messaging.encrypted_fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='ban_reason',
            field=messaging.encrypted_fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='permissions',
            field=messaging.encrypted_fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('user', 'User Message'), ('system', 'System Message'), ('TEXT', 'Texte'), ('IMAGE', 'Image'), ('FILE', 'Fichier'), ('SYSTEM', 'Message système')], default='user', max_length=20),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['timestamp'], name='messaging_m_timesta_bd3028_idx'),
        ),
    ]
