# Generated by Django 5.2.7 on 2026-02-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0015_alter_groupblock_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
