# Generated by Django 5.2.7 on 2026-02-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0016_alter_conversation_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='tags',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
