# Generated by Django 5.2.7 on 2026-02-03 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0018_alter_conversation_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='content_hash',
            new_name='content',
        ),
    ]
