# Generated by Django 5.2.7 on 2026-02-03 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0019_rename_content_hash_conversation_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='content',
            new_name='content_hash',
        ),
    ]
