# Generated by Django 5.2.7 on 2026-02-03 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0020_rename_content_conversation_content_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='encrypted_content',
            new_name='content',
        ),
    ]
