"""
Django settings for spider project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bnt3@*u*vwxxv6aue%*bbs6w+%r#e6!77gl$24$kg$^4*-%f@3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'
 # Mettez True TEMPORAIREMENT pour debugger CORS

ALLOWED_HOSTS = [
    'spider-app-d4d82ba4f1c1.herokuapp.com',
    'localhost',
    '127.0.0.1',
    '.vercel.app',
    '.herokuapp.com'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'feedback_post',
    'accounts',
    'feedback',
    'corsheaders',
    'app',
    'post',
    'comment_post',
    'channels',
    'messaging', 
    'django_filters',
    'report',
    'dashboard_client',
    'searchs',
      'whitenoise.runserver_nostatic',
          'storages',
]
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # DOIT ÊTRE EN PREMIER
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
MIDDLEWARE.insert(0, 'corsheaders.middleware.CorsMiddleware')

ROOT_URLCONF = 'spider.urls'
CORS_ALLOW_CREDENTIALS = True
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'spider.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# settings.py
import os
from pathlib import Path
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.config(default=DATABASE_URL, conn_max_age=600, ssl_require=True)
    }
else:
    # Développement local : SQLite
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    'authorization',
    'content-type',
]
# Liste BLANCHE des domaines autorisés
CORS_ALLOWED_ORIGINS = [
    # Vos domaines Vercel
    "https://spider-r2ci-iluu03k2p-roger-alfanis-projects.vercel.app",
    "https://spider-r2ci-git-master-roger-alfanis-projects.vercel.app",
    "https://spider-r2ci.vercel.app",
    "https://spider.vercel.app",
       "https://spider-v5op-git-master-roger-alfanis-projects.vercel.app", 
    # Développement local
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
]

"""CORS_ALLOWED_ORIGINS = [

    "http://localhost:3000",
    "http://127.0.0.1:3000",
        "http://100.64.6.76:3000",
    "https://100.64.6.76:3000",
       "https://*.ngrok-free.dev",
       "https://brigandishly-metrizable-kenyatta.ngrok-free.dev", ] """
# Si vous utilisez CSRF
CSRF_TRUSTED_ORIGINS = [
    "https://spider-app-d4d82ba4f1c1.herokuapp.com",
    "https://spider-git-master-roger-alfanis-projects.vercel.app",
    "http://localhost:3000",
]
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://[\w-]+-git-master-roger-alfanis-projects\.vercel\.app$",
    r"^https://[\w-]+\.vercel\.app$",
]

# Cookies cross-domain
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False  # ← IMPORTANT : doit être False pour JavaScript
CSRF_COOKIE_SECURE = True  # True pour HTTPS
CORS_ALLOW_CREDENTIALS = False 
# Cookies de session sécurisés
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
# Headers autorisés
CORS_ALLOW_HEADERS = [
    'accept',
    '*',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'access-control-allow-origin',
]
# Dans settings.py - POUR TEST SEULEMENT

# Méthodes autorisées
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# P
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accounts.User'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
DEFAULT_CHARSET = 'utf-8'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'frontend/build'),  # Pour servir React
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]# Détection d'environnement Heroku

# ============== CONFIGURATION S3 UNIFIÉE ==============
# Placez ce bloc APRÈS DATABASES mais AVANT TEMPLATES

# collectstatic_to_s3.py
import os
import sys
import django
from pathlib import Path

# Configuration forcée S3
os.environ['DJANGO_SETTINGS_MODULE'] = 'spider.settings'
os.environ['USE_S3_FOR_COLLECTSTATIC'] = 'true'

# Ajouter le répertoire parent au path

sys.path.insert(0, str(BASE_DIR))

django.setup()

from django.conf import settings
from django.core.management import call_command
import boto3
from boto3.s3.transfer import TransferConfig

print("🔄 COLLECTSTATIC VERS S3 🔄")
print(f"Bucket: {getattr(settings, 'AWS_STORAGE_BUCKET_NAME', 'Non défini')}")
print(f"Storage utilisé: {getattr(settings, 'STATICFILES_STORAGE', 'Non défini')}")

# 1. Vérifier la configuration
if not hasattr(settings, 'AWS_STORAGE_BUCKET_NAME') or not settings.AWS_STORAGE_BUCKET_NAME:
    print("❌ ERREUR: AWS_STORAGE_BUCKET_NAME non configuré")
    sys.exit(1)

# 2. Créer un client S3 pour upload manuel
s3 = boto3.client(
    's3',
    aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
    aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
    region_name=getattr(settings, 'AWS_S3_REGION_NAME', 'eu-west-3')
)

# 3. Récupérer tous les fichiers statiques
from django.contrib.staticfiles.finders import get_finders

all_static_files = []
for finder in get_finders():
    for path, storage in finder.list([]):
        if hasattr(storage, 'path'):
            full_path = storage.path(path)
            if os.path.exists(full_path):
                all_static_files.append((path, full_path))

print(f"📁 {len(all_static_files)} fichiers statiques trouvés")

# 4. Uploader chaque fichier sur S3
uploaded = 0
for static_path, full_path in all_static_files:
    s3_key = f'static/{static_path}'
    
    try:
        # Déterminer content-type
        import mimetypes
        content_type, _ = mimetypes.guess_type(full_path)
        if not content_type:
            content_type = 'application/octet-stream'
        
        # Upload vers S3
        s3.upload_file(
            full_path,
            settings.AWS_STORAGE_BUCKET_NAME,
            s3_key,
            ExtraArgs={
                'ContentType': content_type,
                'CacheControl': 'max-age=86400',
                # Pas d'ACL si le bucket ne les supporte pas
            }
        )
        uploaded += 1
        print(f"  ✅ {s3_key}")
        
    except Exception as e:
        print(f"  ❌ {s3_key}: {e}")

print(f"\n🎉 {uploaded}/{len(all_static_files)} fichiers uploadés sur S3")

# 5. Vérifier sur S3
print("\n📋 Vérification sur S3...")
try:
    response = s3.list_objects_v2(
        Bucket=settings.AWS_STORAGE_BUCKET_NAME,
        Prefix='static/',
        MaxKeys=10
    )
    
    if 'Contents' in response:
        print(f"Fichiers sur S3 ({len(response['Contents'])}):")
        for obj in response['Contents'][:5]:
            print(f"  • {obj['Key']} ({obj['Size']} octets)")
    else:
        print("⚠️  Aucun fichier trouvé sur S3")
        
except Exception as e:
    print(f"❌ Erreur vérification: {e}")
# OBLIGATOIRE : Même avec S3, STATIC_ROOT doit être défini
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# ========== CONFIGURATION S3 ==========
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'eu-north-1')

# Détection Heroku
IS_HEROKU = "DYNO" in os.environ

# Vérifiez si S3 est configuré
S3_ENABLED = all([
    AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY,
    AWS_STORAGE_BUCKET_NAME
])

if S3_ENABLED and IS_HEROKU:
    print(f"🚀 Production Heroku avec S3 - Bucket: {AWS_STORAGE_BUCKET_NAME}")
    
    # 1. FORCER S3 pour tous les fichiers
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    
    # 2. Configuration S3
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }

    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False
    
    # 3. URLs S3
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
    
    # 4. IMPORTANT: Classes custom pour éviter les conflits
    # (Ajoutez cette partie si vous avez encore des problèmes)
    try:
        from storages.backends.s3boto3 import S3Boto3Storage
        
        class StaticS3Storage(S3Boto3Storage):
            location = 'static'

            
        class MediaS3Storage(S3Boto3Storage):
            location = 'media'

            file_overwrite = False
        
        # Utiliser les classes custom
        DEFAULT_FILE_STORAGE = 'spider.settings.MediaS3Storage'
        STATICFILES_STORAGE = 'spider.settings.StaticS3Storage'
        
        print("✅ Classes custom S3 activées")
        
    except ImportError:
        print("⚠️  django-storages non disponible, utilisation des classes par défaut")
    
    # 5. Désactiver whitenoise pour le storage (gardez seulement le middleware)
    
elif IS_HEROKU:
    print("⚠️  Heroku sans S3 - Utilisation de WhiteNoise")
    # Configuration Heroku sans S3
    STATIC_URL = '/static/'
    MEDIA_URL = '/media/'
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    
else:
    print("💻 Mode développement local")
    # Configuration locale
    STATIC_URL = '/static/'
    MEDIA_URL = '/media/'
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# ============== FIN CONFIGURATION S3 ==============

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
         'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
   ],
}


# settings.py
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

SITE_NAME = 'Spider App'  # ou le nom de votre application
SITE_URL = 'http://localhost:3000'  # URL de votre frontend
DEFAULT_FROM_EMAIL = 'noreply@yourdomain.com'  # Email d'envoi
# Types de fichiers autorisés
ALLOWED_IMAGE_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif', 'webp']
ALLOWED_VIDEO_EXTENSIONS = ['mp4', 'avi', 'mov', 'mkv', 'webm']
ALLOWED_FILE_EXTENSIONS = ['pdf', 'doc', 'docx', 'txt', 'zip']
# CSRF trusted origins
CSRF_TRUSTED_ORIGINS = [
    "https://spider-r2ci.vercel.app",
    "https://*.vercel.app",
]

# Configuration pour Heroku Postgres (si vous l'utilisez)
#db_from_env = dj_database_url.config(conn_max_age=600)
#DATABASES['default'].update(db_from_env)

# settings.py


# ========== CHARGEMENT DU .env ==========
ENV_PATH = BASE_DIR / '.env'
if ENV_PATH.exists():
    print(f"✅ Fichier .env trouvé : {ENV_PATH}")
    with open(ENV_PATH, 'r') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#'):
                if '=' in line:
                    key, value = line.split('=', 1)
                    os.environ[key.strip()] = value.strip().strip('"').strip("'")
else:
    print("⚠️ Fichier .env non trouvé. Créez-en un avec vos identifiants email.")


# ========== CONFIGURATION EMAIL POUR ENVOI RÉEL ==========

# FORCER l'envoi SMTP réel (pas de console en DEBUG)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'rogeralfani149@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# Nom du site
SITE_NAME = os.environ.get('SITE_NAME', 'Spider')

# Timeout pour éviter les blocages
EMAIL_TIMEOUT = 30  # secondes

# IMPORTANT: DÉSACTIVER le mode console même en DEBUG
# SUPPRIMEZ ou COMMENTER cette ligne :
# if DEBUG:
#     EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
"""
print("=" * 50)
print("📧 CONFIGURATION EMAIL POUR ENVOI RÉEL")
print("=" * 50)
print(f"Serveur SMTP : {EMAIL_HOST}:{EMAIL_PORT}")
print(f"Utilisateur : {EMAIL_HOST_USER}")
print(f"Expéditeur : {DEFAULT_FROM_EMAIL}")
print(f"TLS activé : {EMAIL_USE_TLS}")
print(f"Backend : {EMAIL_BACKEND}")
print("=" * 50)

if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
    print("❌ ATTENTION : EMAIL_HOST_USER ou EMAIL_HOST_PASSWORD est vide!")
    print("❌ Les emails ne pourront pas être envoyés.")
    print("❌ Vérifiez votre fichier .env") 
    """


# Logging configuration pour debugger CORS
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'corsheaders': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}
