"""
Django settings for spider project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings
SECRET_KEY = 'django-insecure-bnt3@*u*vwxxv6aue%*bbs6w+%r#e6!77gl$24$kg$^4*-%f@3'
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    'spider-app-d4d82ba4f1c1.herokuapp.com',
    'localhost',
    '127.0.0.1',
    '.vercel.app',
    '.herokuapp.com'
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'feedback_post',
    'accounts',
    'feedback',
    'corsheaders',
    'app',
    'post',
    'comment_post',
    'channels',
    'messaging', 
    'django_filters',
    'report',
    'dashboard_client',
    'searchs',
    'whitenoise.runserver_nostatic',
    'storages',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'spider.urls'
CORS_ALLOW_CREDENTIALS = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'frontend/build'),
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'spider.wsgi.application'

# Database
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Détection environnement Heroku
IS_HEROKU = "DYNO" in os.environ

if IS_HEROKU:
    DATABASE_URL = os.environ.get("DATABASE_URL")
    if DATABASE_URL:
        DATABASES = {
            "default": dj_database_url.config(default=DATABASE_URL, conn_max_age=600, ssl_require=True)
        }
    else:
        raise ValueError("DATABASE_URL non défini sur Heroku")
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# CORS Configuration
from corsheaders.defaults import default_headers

CORS_ALLOWED_ORIGINS = [
    "https://spider-r2ci-iluu03k2p-roger-alfanis-projects.vercel.app",
    "https://spider-r2ci-git-master-roger-alfanis-projects.vercel.app",
    "https://spider-r2ci.vercel.app",
    "https://spider.vercel.app",
    "https://spider-v5op-git-master-roger-alfanis-projects.vercel.app", 
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
]

CSRF_TRUSTED_ORIGINS = [
    "https://spider-app-d4d82ba4f1c1.herokuapp.com",
    "https://spider-git-master-roger-alfanis-projects.vercel.app",
    "http://localhost:3000",
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://[\w-]+-git-master-roger-alfanis-projects\.vercel\.app$",
    r"^https://[\w-]+\.vercel\.app$",
]

CORS_ALLOW_HEADERS = list(default_headers) + ['authorization', 'content-type']
CORS_ALLOW_METHODS = ['DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT']

CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = True
CORS_ALLOW_CREDENTIALS = False
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

AUTH_USER_MODEL = 'accounts.User'

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
DEFAULT_CHARSET = 'utf-8'

# ========== CONFIGURATION S3 SIMPLIFIÉE ==========
# =========== CONFIGURATION FICHIERS ===========

# Variables S3 depuis l'environnement (TOUJOURS LES LIRE)
#STATIC_URL = 'static/'
STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles', 'static')
#MEDIA_URLS ='/media/'
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"


AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME", "eu-north-1")
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_SIGNATURE_NAME = 's3v4',
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL =  None
AWS_S3_VERIFY = True
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Si sur Heroku ET S3 configuré

"""   
if IS_HEROKU and AWS_STORAGE_BUCKET_NAME and AWS_ACCESS_KEY_ID:
    print(f"🚀 Activation S3 pour Heroku - Bucket: {AWS_STORAGE_BUCKET_NAME}")
    
    # =========== CONFIGURATION S3 (PAS DE FICHIERS LOCAUX) ===========
    
    # Configuration S3
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    
    # Domaine S3
    AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"
    
    # URLs S3
    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"
    
    # Stockages S3
    DEFAULT_FILE_STORAGE = 'spider.storage_backends.MediaStorage'
    STATICFILES_STORAGE = 'spider.storage_backends.StaticStorage'
    
    # ⚠️ IMPORTANT : NE PAS DÉFINIR STATIC_ROOT et MEDIA_ROOT quand on utilise S3 !
    # Les laisser non définis ou les définir comme chaînes vides
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_tmp')# OU ne pas le définir du tout
    MEDIA_ROOT = ''   # OU ne pas le définir du tout
    
    # Désactiver WhiteNoise
    MIDDLEWARE = [m for m in MIDDLEWARE if 'WhiteNoiseMiddleware' not in str(m)]
    
    print("✅ Configuration S3 complète - Stockage exclusivement sur S3")
    
else:
    # =========== CONFIGURATION LOCALE (DÉVELOPPEMENT) ===========
    print("💻 Mode local - Stockage fichiers locaux")
    
    # URLs locales
    STATIC_URL = '/static/'
    MEDIA_URL = '/media/'
    
    # Stockages locaux
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
    
    # Chemins locaux (UNIQUEMENT en mode local)
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    
    # WhiteNoise pour Heroku sans S3
    if IS_HEROKU:
        STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

"""        
# REST Framework

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

# Email configuration
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

SITE_NAME = 'Spider App'
SITE_URL = 'http://localhost:3000'
DEFAULT_FROM_EMAIL = 'noreply@yourdomain.com'

# File upload configurations
ALLOWED_IMAGE_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif', 'webp']
ALLOWED_VIDEO_EXTENSIONS = ['mp4', 'avi', 'mov', 'mkv', 'webm']
ALLOWED_FILE_EXTENSIONS = ['pdf', 'doc', 'docx', 'txt', 'zip']

# CSRF trusted origins
CSRF_TRUSTED_ORIGINS = [
    "https://spider-r2ci.vercel.app",
    "https://*.vercel.app",
]
# ========== CONFIGURATION EMAIL POUR ENVOI RÉEL ==========

# FORCER l'envoi SMTP réel (pas de console en DEBUG)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'rogeralfani149@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# Nom du site
SITE_NAME = os.environ.get('SITE_NAME', 'Spider')

# Timeout pour éviter les blocages
EMAIL_TIMEOUT = 30  # secondes

# IMPORTANT: DÉSACTIVER le mode console même en DEBUG
# SUPPRIMEZ ou COMMENTER cette ligne :
# if DEBUG:
#     EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
"""
print("=" * 50)
print("📧 CONFIGURATION EMAIL POUR ENVOI RÉEL")
print("=" * 50)
print(f"Serveur SMTP : {EMAIL_HOST}:{EMAIL_PORT}")
print(f"Utilisateur : {EMAIL_HOST_USER}")
print(f"Expéditeur : {DEFAULT_FROM_EMAIL}")
print(f"TLS activé : {EMAIL_USE_TLS}")
print(f"Backend : {EMAIL_BACKEND}")
print("=" * 50)

if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
    print("❌ ATTENTION : EMAIL_HOST_USER ou EMAIL_HOST_PASSWORD est vide!")
    print("❌ Les emails ne pourront pas être envoyés.")
    print("❌ Vérifiez votre fichier .env") 
    """


# Logging configuration pour debugger CORS
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'corsheaders': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}
